// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingApp.Data;

#nullable disable

namespace TradingApp.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260824134450_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingApp.Models.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetClass")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetClass = 0,
                            Currency = "USD",
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            AssetClass = 0,
                            Currency = "USD",
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 3,
                            AssetClass = 1,
                            Currency = "EUR",
                            Symbol = "EURUSD"
                        },
                        new
                        {
                            Id = 4,
                            AssetClass = 1,
                            Currency = "GBP",
                            Symbol = "GBPUSD"
                        });
                });

            modelBuilder.Entity("TradingApp.Models.MarketPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("MarketPrices");
                });

            modelBuilder.Entity("TradingApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("LimitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TraderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("TraderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TradingApp.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<DateTime>("TradeTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("OrderId");

                    b.HasIndex("TraderId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("TradingApp.Models.Trader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxOrderNotional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Traders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desk = "Equity",
                            MaxOrderNotional = 1000000m,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Desk = "FX",
                            MaxOrderNotional = 5000000m,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Desk = "Equity",
                            MaxOrderNotional = 2000000m,
                            Name = "Charlie"
                        });
                });

            modelBuilder.Entity("TradingApp.Models.MarketPrice", b =>
                {
                    b.HasOne("TradingApp.Models.Instrument", "Instrument")
                        .WithMany("MarketPrices")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradingApp.Models.Order", b =>
                {
                    b.HasOne("TradingApp.Models.Instrument", "Instrument")
                        .WithMany("Orders")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingApp.Models.Trader", "Trader")
                        .WithMany("Orders")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("TradingApp.Models.Trade", b =>
                {
                    b.HasOne("TradingApp.Models.Instrument", "Instrument")
                        .WithMany("Trades")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingApp.Models.Order", "Order")
                        .WithMany("Trades")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingApp.Models.Trader", "Trader")
                        .WithMany("Trades")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Order");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("TradingApp.Models.Instrument", b =>
                {
                    b.Navigation("MarketPrices");

                    b.Navigation("Orders");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("TradingApp.Models.Order", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("TradingApp.Models.Trader", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
